name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3.3.0
